/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
        /// <summary>
        /// Represents a type of action that can occur on a access request
        /// </summary>
        /// <value>Represents a type of action that can occur on a access request</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum AccessRequestStateAction
        {
            /// <summary>
            /// Enum AcknowledgeRequestEnum for AcknowledgeRequest
            /// </summary>
            [EnumMember(Value = "AcknowledgeRequest")]
            AcknowledgeRequestEnum = 0,
            /// <summary>
            /// Enum ApproveRequestEnum for ApproveRequest
            /// </summary>
            [EnumMember(Value = "ApproveRequest")]
            ApproveRequestEnum = 1,
            /// <summary>
            /// Enum CancelRequestEnum for CancelRequest
            /// </summary>
            [EnumMember(Value = "CancelRequest")]
            CancelRequestEnum = 2,
            /// <summary>
            /// Enum CheckInRequestEnum for CheckInRequest
            /// </summary>
            [EnumMember(Value = "CheckInRequest")]
            CheckInRequestEnum = 3,
            /// <summary>
            /// Enum CheckOutPasswordEnum for CheckOutPassword
            /// </summary>
            [EnumMember(Value = "CheckOutPassword")]
            CheckOutPasswordEnum = 4,
            /// <summary>
            /// Enum CloseRequestWithoutReviewEnum for CloseRequestWithoutReview
            /// </summary>
            [EnumMember(Value = "CloseRequestWithoutReview")]
            CloseRequestWithoutReviewEnum = 5,
            /// <summary>
            /// Enum DenyRequestEnum for DenyRequest
            /// </summary>
            [EnumMember(Value = "DenyRequest")]
            DenyRequestEnum = 6,
            /// <summary>
            /// Enum EvictRequestEnum for EvictRequest
            /// </summary>
            [EnumMember(Value = "EvictRequest")]
            EvictRequestEnum = 7,
            /// <summary>
            /// Enum ExpireRequestEnum for ExpireRequest
            /// </summary>
            [EnumMember(Value = "ExpireRequest")]
            ExpireRequestEnum = 8,
            /// <summary>
            /// Enum InitializeEnum for Initialize
            /// </summary>
            [EnumMember(Value = "Initialize")]
            InitializeEnum = 9,
            /// <summary>
            /// Enum PasswordWasResetEnum for PasswordWasReset
            /// </summary>
            [EnumMember(Value = "PasswordWasReset")]
            PasswordWasResetEnum = 10,
            /// <summary>
            /// Enum ReviewRequestEnum for ReviewRequest
            /// </summary>
            [EnumMember(Value = "ReviewRequest")]
            ReviewRequestEnum = 11,
            /// <summary>
            /// Enum RevokeRequestEnum for RevokeRequest
            /// </summary>
            [EnumMember(Value = "RevokeRequest")]
            RevokeRequestEnum = 12,
            /// <summary>
            /// Enum TimeRequestedArrivedEnum for TimeRequestedArrived
            /// </summary>
            [EnumMember(Value = "TimeRequestedArrived")]
            TimeRequestedArrivedEnum = 13,
            /// <summary>
            /// Enum NextStateEnum for NextState
            /// </summary>
            [EnumMember(Value = "NextState")]
            NextStateEnum = 14,
            /// <summary>
            /// Enum InitializeSessionEnum for InitializeSession
            /// </summary>
            [EnumMember(Value = "InitializeSession")]
            InitializeSessionEnum = 15,
            /// <summary>
            /// Enum AuthenticateSessionEnum for AuthenticateSession
            /// </summary>
            [EnumMember(Value = "AuthenticateSession")]
            AuthenticateSessionEnum = 16,
            /// <summary>
            /// Enum AuthorizeSessionEnum for AuthorizeSession
            /// </summary>
            [EnumMember(Value = "AuthorizeSession")]
            AuthorizeSessionEnum = 17,
            /// <summary>
            /// Enum CheckOutSessionPasswordEnum for CheckOutSessionPassword
            /// </summary>
            [EnumMember(Value = "CheckOutSessionPassword")]
            CheckOutSessionPasswordEnum = 18,
            /// <summary>
            /// Enum TerminateSessionEnum for TerminateSession
            /// </summary>
            [EnumMember(Value = "TerminateSession")]
            TerminateSessionEnum = 19,
            /// <summary>
            /// Enum AuditSessionEnum for AuditSession
            /// </summary>
            [EnumMember(Value = "AuditSession")]
            AuditSessionEnum = 20,
            /// <summary>
            /// Enum InitializeSessionPlaybackEnum for InitializeSessionPlayback
            /// </summary>
            [EnumMember(Value = "InitializeSessionPlayback")]
            InitializeSessionPlaybackEnum = 21,
            /// <summary>
            /// Enum AccountWasSuspendedEnum for AccountWasSuspended
            /// </summary>
            [EnumMember(Value = "AccountWasSuspended")]
            AccountWasSuspendedEnum = 22,
            /// <summary>
            /// Enum AccountWasRestoredEnum for AccountWasRestored
            /// </summary>
            [EnumMember(Value = "AccountWasRestored")]
            AccountWasRestoredEnum = 23,
            /// <summary>
            /// Enum CloseRequestEnum for CloseRequest
            /// </summary>
            [EnumMember(Value = "CloseRequest")]
            CloseRequestEnum = 24,
            /// <summary>
            /// Enum PasswordResetByPassedEnum for PasswordResetByPassed
            /// </summary>
            [EnumMember(Value = "PasswordResetByPassed")]
            PasswordResetByPassedEnum = 25,
            /// <summary>
            /// Enum CheckOutSshKeyEnum for CheckOutSshKey
            /// </summary>
            [EnumMember(Value = "CheckOutSshKey")]
            CheckOutSshKeyEnum = 26,
            /// <summary>
            /// Enum SshKeyWasResetEnum for SshKeyWasReset
            /// </summary>
            [EnumMember(Value = "SshKeyWasReset")]
            SshKeyWasResetEnum = 27,
            /// <summary>
            /// Enum SshKeyResetBypassedEnum for SshKeyResetBypassed
            /// </summary>
            [EnumMember(Value = "SshKeyResetBypassed")]
            SshKeyResetBypassedEnum = 28,
            /// <summary>
            /// Enum CheckOutSessionSshKeyEnum for CheckOutSessionSshKey
            /// </summary>
            [EnumMember(Value = "CheckOutSessionSshKey")]
            CheckOutSessionSshKeyEnum = 29        }
}
