/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
        /// <summary>
        /// Type of asset discovery job
        /// </summary>
        /// <value>Type of asset discovery job</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum AssetDiscoveryType
        {
            /// <summary>
            /// Enum DirectoryEnum for Directory
            /// </summary>
            [EnumMember(Value = "Directory")]
            DirectoryEnum = 0,
            /// <summary>
            /// Enum NetworkEnum for Network
            /// </summary>
            [EnumMember(Value = "Network")]
            NetworkEnum = 1        }
}
