/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
        /// <summary>
        /// Type of directory account discovery filter
        /// </summary>
        /// <value>Type of directory account discovery filter</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DirectoryAccountDiscoveryRuleType
        {
            /// <summary>
            /// Enum NameEnum for Name
            /// </summary>
            [EnumMember(Value = "Name")]
            NameEnum = 0,
            /// <summary>
            /// Enum GroupEnum for Group
            /// </summary>
            [EnumMember(Value = "Group")]
            GroupEnum = 1,
            /// <summary>
            /// Enum PropertyConstraintEnum for PropertyConstraint
            /// </summary>
            [EnumMember(Value = "PropertyConstraint")]
            PropertyConstraintEnum = 2,
            /// <summary>
            /// Enum LdapFilterEnum for LdapFilter
            /// </summary>
            [EnumMember(Value = "LdapFilter")]
            LdapFilterEnum = 3,
            /// <summary>
            /// Enum FindAllEnum for FindAll
            /// </summary>
            [EnumMember(Value = "FindAll")]
            FindAllEnum = 4        }
}
