/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
        /// <summary>
        /// Gets or Sets DiscoveredAccountStatus
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DiscoveredAccountStatus
        {
            /// <summary>
            /// Enum NoneEnum for None
            /// </summary>
            [EnumMember(Value = "None")]
            NoneEnum = 0,
            /// <summary>
            /// Enum DeletedEnum for Deleted
            /// </summary>
            [EnumMember(Value = "Deleted")]
            DeletedEnum = 1,
            /// <summary>
            /// Enum IgnoredEnum for Ignored
            /// </summary>
            [EnumMember(Value = "Ignored")]
            IgnoredEnum = 2,
            /// <summary>
            /// Enum ManagedEnum for Managed
            /// </summary>
            [EnumMember(Value = "Managed")]
            ManagedEnum = 3,
            /// <summary>
            /// Enum DisabledEnum for Disabled
            /// </summary>
            [EnumMember(Value = "Disabled")]
            DisabledEnum = 4        }
}
