/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class HardwareSecurityModuleClientCertificate : IEquatable<HardwareSecurityModuleClientCertificate>
    { 
        /// <summary>
        /// Gets or Sets ClientPem
        /// </summary>

        [DataMember(Name="ClientPem")]
        public string ClientPem { get; set; }

        /// <summary>
        /// Gets or Sets ClientKey
        /// </summary>

        [DataMember(Name="ClientKey")]
        public string ClientKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HardwareSecurityModuleClientCertificate {\n");
            sb.Append("  ClientPem: ").Append(ClientPem).Append("\n");
            sb.Append("  ClientKey: ").Append(ClientKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((HardwareSecurityModuleClientCertificate)obj);
        }

        /// <summary>
        /// Returns true if HardwareSecurityModuleClientCertificate instances are equal
        /// </summary>
        /// <param name="other">Instance of HardwareSecurityModuleClientCertificate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HardwareSecurityModuleClientCertificate other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ClientPem == other.ClientPem ||
                    ClientPem != null &&
                    ClientPem.Equals(other.ClientPem)
                ) && 
                (
                    ClientKey == other.ClientKey ||
                    ClientKey != null &&
                    ClientKey.Equals(other.ClientKey)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ClientPem != null)
                    hashCode = hashCode * 59 + ClientPem.GetHashCode();
                    if (ClientKey != null)
                    hashCode = hashCode * 59 + ClientKey.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(HardwareSecurityModuleClientCertificate left, HardwareSecurityModuleClientCertificate right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(HardwareSecurityModuleClientCertificate left, HardwareSecurityModuleClientCertificate right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
