/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
    /// <summary>
    /// When the TypeReferenceName property is \&quot;ExternalFederation\&quot;, this provides additional configuration values              specific to that type.
    /// </summary>
    [DataContract]
    public partial class IdentityProviderConfigExternalFederationProperties : IEquatable<IdentityProviderConfigExternalFederationProperties>
    { 
        /// <summary>
        /// The DNS suffix name(s) for which the Pangaea.Data.Transfer.V2.Users.IdentityProviderConfigExternalFederationProperties.FederationMetadata is applicable to.  This value needs to match              the email address suffix of a user that intends to be authenticated. If the federated authentication supports more than              one realm, enter each realm separated by a space, comma, or new line.
        /// </summary>
        /// <value>The DNS suffix name(s) for which the Pangaea.Data.Transfer.V2.Users.IdentityProviderConfigExternalFederationProperties.FederationMetadata is applicable to.  This value needs to match              the email address suffix of a user that intends to be authenticated. If the federated authentication supports more than              one realm, enter each realm separated by a space, comma, or new line.</value>

        [MaxLength(16777216)]
        [DataMember(Name="Realm")]
        public string Realm { get; set; }

        /// <summary>
        /// The complete federation metadata Xml of the Identity Provider STS that a user will be redirected to for              authentication.
        /// </summary>
        /// <value>The complete federation metadata Xml of the Identity Provider STS that a user will be redirected to for              authentication.</value>

        [MaxLength(16777216)]
        [DataMember(Name="FederationMetadata")]
        public string FederationMetadata { get; set; }

        /// <summary>
        /// The {RequestedAuthnContext} in a SAML2 request, asking the IdP to authenticate the user with              a specified authentication mechanism. For example, {urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport}.              If specified, use one or more of the allowed context class URIs from the saml-authn-context-2.0-os.pdf              (https://docs.oasis-open.org/security/saml/v2.0/saml-authn-context-2.0-os.pdf), section 3.4 Schemas.              Specify multiple values by separating the strings with a space or comma.
        /// </summary>
        /// <value>The {RequestedAuthnContext} in a SAML2 request, asking the IdP to authenticate the user with              a specified authentication mechanism. For example, {urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport}.              If specified, use one or more of the allowed context class URIs from the saml-authn-context-2.0-os.pdf              (https://docs.oasis-open.org/security/saml/v2.0/saml-authn-context-2.0-os.pdf), section 3.4 Schemas.              Specify multiple values by separating the strings with a space or comma.</value>

        [MaxLength(2048)]
        [DataMember(Name="AuthnContextClasses")]
        public string AuthnContextClasses { get; set; }

        /// <summary>
        /// Gets or Sets AuthnContextComparison
        /// </summary>

        [DataMember(Name="AuthnContextComparison")]
        public AuthnContextComparison AuthnContextComparison { get; set; }

        /// <summary>
        /// The {Format} attribute of the {NameID} element within the {Issuer} element of a              SAML2 AuthnRequest. For example, {urn:oasis:names:tc:SAML:2.0:nameid-format:entity}. If specified,              use one of the allowed name identifier format identifiers as listed in section 8.3 of Assertions and              Protocols for the OASIS Security Assertion Markup Language (SAML) V2.0 – Errata Composite.
        /// </summary>
        /// <value>The {Format} attribute of the {NameID} element within the {Issuer} element of a              SAML2 AuthnRequest. For example, {urn:oasis:names:tc:SAML:2.0:nameid-format:entity}. If specified,              use one of the allowed name identifier format identifiers as listed in section 8.3 of Assertions and              Protocols for the OASIS Security Assertion Markup Language (SAML) V2.0 – Errata Composite.</value>

        [MaxLength(255)]
        [DataMember(Name="NameIDFormat")]
        public string NameIDFormat { get; set; }

        /// <summary>
        /// Controls the {ForceAuthn} attribute of a SAML2 AuthnRequest. When set to true, the user              will be required to reenter their credentials on the external federation site, even if they are already              logged in, thus negating any single sign-on benefits, but may be considered more secure.                            If not specified/included in the request when creating a new instance, the default value will be true.
        /// </summary>
        /// <value>Controls the {ForceAuthn} attribute of a SAML2 AuthnRequest. When set to true, the user              will be required to reenter their credentials on the external federation site, even if they are already              logged in, thus negating any single sign-on benefits, but may be considered more secure.                            If not specified/included in the request when creating a new instance, the default value will be true.</value>

        [DataMember(Name="RequireAuthentication")]
        public bool? RequireAuthentication { get; set; }

        /// <summary>
        /// Override the {Issuer} name value sent in a SAML2 AuthnRequest.
        /// </summary>
        /// <value>Override the {Issuer} name value sent in a SAML2 AuthnRequest.</value>

        [DataMember(Name="ApplicationIdOverride")]
        public string ApplicationIdOverride { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IdentityProviderConfigExternalFederationProperties {\n");
            sb.Append("  Realm: ").Append(Realm).Append("\n");
            sb.Append("  FederationMetadata: ").Append(FederationMetadata).Append("\n");
            sb.Append("  AuthnContextClasses: ").Append(AuthnContextClasses).Append("\n");
            sb.Append("  AuthnContextComparison: ").Append(AuthnContextComparison).Append("\n");
            sb.Append("  NameIDFormat: ").Append(NameIDFormat).Append("\n");
            sb.Append("  RequireAuthentication: ").Append(RequireAuthentication).Append("\n");
            sb.Append("  ApplicationIdOverride: ").Append(ApplicationIdOverride).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((IdentityProviderConfigExternalFederationProperties)obj);
        }

        /// <summary>
        /// Returns true if IdentityProviderConfigExternalFederationProperties instances are equal
        /// </summary>
        /// <param name="other">Instance of IdentityProviderConfigExternalFederationProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IdentityProviderConfigExternalFederationProperties other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Realm == other.Realm ||
                    Realm != null &&
                    Realm.Equals(other.Realm)
                ) && 
                (
                    FederationMetadata == other.FederationMetadata ||
                    FederationMetadata != null &&
                    FederationMetadata.Equals(other.FederationMetadata)
                ) && 
                (
                    AuthnContextClasses == other.AuthnContextClasses ||
                    AuthnContextClasses != null &&
                    AuthnContextClasses.Equals(other.AuthnContextClasses)
                ) && 
                (
                    AuthnContextComparison == other.AuthnContextComparison ||
                    AuthnContextComparison != null &&
                    AuthnContextComparison.Equals(other.AuthnContextComparison)
                ) && 
                (
                    NameIDFormat == other.NameIDFormat ||
                    NameIDFormat != null &&
                    NameIDFormat.Equals(other.NameIDFormat)
                ) && 
                (
                    RequireAuthentication == other.RequireAuthentication ||
                    RequireAuthentication != null &&
                    RequireAuthentication.Equals(other.RequireAuthentication)
                ) && 
                (
                    ApplicationIdOverride == other.ApplicationIdOverride ||
                    ApplicationIdOverride != null &&
                    ApplicationIdOverride.Equals(other.ApplicationIdOverride)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Realm != null)
                    hashCode = hashCode * 59 + Realm.GetHashCode();
                    if (FederationMetadata != null)
                    hashCode = hashCode * 59 + FederationMetadata.GetHashCode();
                    if (AuthnContextClasses != null)
                    hashCode = hashCode * 59 + AuthnContextClasses.GetHashCode();
                    if (AuthnContextComparison != null)
                    hashCode = hashCode * 59 + AuthnContextComparison.GetHashCode();
                    if (NameIDFormat != null)
                    hashCode = hashCode * 59 + NameIDFormat.GetHashCode();
                    if (RequireAuthentication != null)
                    hashCode = hashCode * 59 + RequireAuthentication.GetHashCode();
                    if (ApplicationIdOverride != null)
                    hashCode = hashCode * 59 + ApplicationIdOverride.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(IdentityProviderConfigExternalFederationProperties left, IdentityProviderConfigExternalFederationProperties right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(IdentityProviderConfigExternalFederationProperties left, IdentityProviderConfigExternalFederationProperties right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
