/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
    /// <summary>
    /// Represents a Login Message.
    /// </summary>
    [DataContract]
    public partial class LoginMessage : IEquatable<LoginMessage>
    { 
        /// <summary>
        /// Gets or Sets Message
        /// </summary>

        [MaxLength(512)]
        [DataMember(Name="Message")]
        public string Message { get; set; }

        /// <summary>
        /// Date this entity was updated (Read-only)
        /// </summary>
        /// <value>Date this entity was updated (Read-only)</value>

        [DataMember(Name="UpdatedDate")]
        public DateTime? UpdatedDate { get; set; }

        /// <summary>
        /// The database ID of the user that updated this entity (Read-only)
        /// </summary>
        /// <value>The database ID of the user that updated this entity (Read-only)</value>

        [DataMember(Name="UpdatedByUserId")]
        public int? UpdatedByUserId { get; set; }

        /// <summary>
        /// The display name of the user that updated this entity (Read-only)
        /// </summary>
        /// <value>The display name of the user that updated this entity (Read-only)</value>

        [DataMember(Name="UpdatedByUserDisplayName")]
        public string UpdatedByUserDisplayName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LoginMessage {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  UpdatedDate: ").Append(UpdatedDate).Append("\n");
            sb.Append("  UpdatedByUserId: ").Append(UpdatedByUserId).Append("\n");
            sb.Append("  UpdatedByUserDisplayName: ").Append(UpdatedByUserDisplayName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LoginMessage)obj);
        }

        /// <summary>
        /// Returns true if LoginMessage instances are equal
        /// </summary>
        /// <param name="other">Instance of LoginMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LoginMessage other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Message == other.Message ||
                    Message != null &&
                    Message.Equals(other.Message)
                ) && 
                (
                    UpdatedDate == other.UpdatedDate ||
                    UpdatedDate != null &&
                    UpdatedDate.Equals(other.UpdatedDate)
                ) && 
                (
                    UpdatedByUserId == other.UpdatedByUserId ||
                    UpdatedByUserId != null &&
                    UpdatedByUserId.Equals(other.UpdatedByUserId)
                ) && 
                (
                    UpdatedByUserDisplayName == other.UpdatedByUserDisplayName ||
                    UpdatedByUserDisplayName != null &&
                    UpdatedByUserDisplayName.Equals(other.UpdatedByUserDisplayName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                    if (UpdatedDate != null)
                    hashCode = hashCode * 59 + UpdatedDate.GetHashCode();
                    if (UpdatedByUserId != null)
                    hashCode = hashCode * 59 + UpdatedByUserId.GetHashCode();
                    if (UpdatedByUserDisplayName != null)
                    hashCode = hashCode * 59 + UpdatedByUserDisplayName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LoginMessage left, LoginMessage right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LoginMessage left, LoginMessage right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
