/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
    /// <summary>
    /// Properties used when using Network DiscoveryType
    /// </summary>
    [DataContract]
    public partial class NetworkDiscoveryProperties : IEquatable<NetworkDiscoveryProperties>
    { 
        /// <summary>
        /// Gets or Sets ScanOptions
        /// </summary>

        [DataMember(Name="ScanOptions")]
        public NetworkDiscoveryOptions ScanOptions { get; set; }

        /// <summary>
        /// Set of ip ranges to apply to the network asset discovery query
        /// </summary>
        /// <value>Set of ip ranges to apply to the network asset discovery query</value>
        [Required]

        [DataMember(Name="ScanRules")]
        public List<AssetDiscoveryNetScanRule> ScanRules { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NetworkDiscoveryProperties {\n");
            sb.Append("  ScanOptions: ").Append(ScanOptions).Append("\n");
            sb.Append("  ScanRules: ").Append(ScanRules).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((NetworkDiscoveryProperties)obj);
        }

        /// <summary>
        /// Returns true if NetworkDiscoveryProperties instances are equal
        /// </summary>
        /// <param name="other">Instance of NetworkDiscoveryProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NetworkDiscoveryProperties other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ScanOptions == other.ScanOptions ||
                    ScanOptions != null &&
                    ScanOptions.Equals(other.ScanOptions)
                ) && 
                (
                    ScanRules == other.ScanRules ||
                    ScanRules != null &&
                    ScanRules.SequenceEqual(other.ScanRules)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ScanOptions != null)
                    hashCode = hashCode * 59 + ScanOptions.GetHashCode();
                    if (ScanRules != null)
                    hashCode = hashCode * 59 + ScanRules.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(NetworkDiscoveryProperties left, NetworkDiscoveryProperties right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(NetworkDiscoveryProperties left, NetworkDiscoveryProperties right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
