/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
        /// <summary>
        /// Types of entitlement reports
        /// </summary>
        /// <value>Types of entitlement reports</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum OwnershipReportTypes
        {
            /// <summary>
            /// Enum UserEnum for User
            /// </summary>
            [EnumMember(Value = "User")]
            UserEnum = 0,
            /// <summary>
            /// Enum AssetEnum for Asset
            /// </summary>
            [EnumMember(Value = "Asset")]
            AssetEnum = 1,
            /// <summary>
            /// Enum AccountEnum for Account
            /// </summary>
            [EnumMember(Value = "Account")]
            AccountEnum = 2,
            /// <summary>
            /// Enum PartitionEnum for Partition
            /// </summary>
            [EnumMember(Value = "Partition")]
            PartitionEnum = 3,
            /// <summary>
            /// Enum TagEnum for Tag
            /// </summary>
            [EnumMember(Value = "Tag")]
            TagEnum = 4        }
}
