/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
        /// <summary>
        /// Represents the type of character in reference to password rules
        /// </summary>
        /// <value>Represents the type of character in reference to password rules</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PasswordCharacterType
        {
            /// <summary>
            /// Enum AllEnum for All
            /// </summary>
            [EnumMember(Value = "All")]
            AllEnum = 0,
            /// <summary>
            /// Enum AlphaNumericEnum for AlphaNumeric
            /// </summary>
            [EnumMember(Value = "AlphaNumeric")]
            AlphaNumericEnum = 1,
            /// <summary>
            /// Enum AlphabeticEnum for Alphabetic
            /// </summary>
            [EnumMember(Value = "Alphabetic")]
            AlphabeticEnum = 2        }
}
