/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
    /// <summary>
    /// Represents a schedule used by a partition profile to change passwords
    /// </summary>
    [DataContract]
    public partial class PasswordChangeSchedule : IEquatable<PasswordChangeSchedule>
    { 
        /// <summary>
        /// Name of this schedule
        /// </summary>
        /// <value>Name of this schedule</value>
        [Required]

        [StringLength(70, MinimumLength=1)]
        [DataMember(Name="Name")]
        public string Name { get; set; }

        /// <summary>
        /// Flag allowing the password to be changed when it has been checked out. Not applicable to accounts in a password sync group.
        /// </summary>
        /// <value>Flag allowing the password to be changed when it has been checked out. Not applicable to accounts in a password sync group.</value>

        [DataMember(Name="AllowPasswordChangeWhenReleased")]
        public bool? AllowPasswordChangeWhenReleased { get; set; }

        /// <summary>
        /// Whether an account should be suspended when it is checked in. Will be restored when made available for check out.
        /// </summary>
        /// <value>Whether an account should be suspended when it is checked in. Will be restored when made available for check out.</value>

        [DataMember(Name="SuspendAccountWhenCheckedIn")]
        public bool? SuspendAccountWhenCheckedIn { get; set; }

        /// <summary>
        /// Only notify account owners that password must be changed or account must be restored/suspended rather than running immediately
        /// </summary>
        /// <value>Only notify account owners that password must be changed or account must be restored/suspended rather than running immediately</value>

        [DataMember(Name="NotifyOwnersOnly")]
        public bool? NotifyOwnersOnly { get; set; }

        /// <summary>
        /// Whether to allow use of the current account password when managing passwords on platforms that support it
        /// </summary>
        /// <value>Whether to allow use of the current account password when managing passwords on platforms that support it</value>

        [DataMember(Name="RequireCurrentPassword")]
        public bool? RequireCurrentPassword { get; set; }

        /// <summary>
        /// Flag allowing windows service to be restarted when a password is changed
        /// </summary>
        /// <value>Flag allowing windows service to be restarted when a password is changed</value>

        [DataMember(Name="RestartWindowsServiceOnPasswordChange")]
        public bool? RestartWindowsServiceOnPasswordChange { get; set; }

        /// <summary>
        /// Flag allowing windows service to be updated when a password is changed
        /// </summary>
        /// <value>Flag allowing windows service to be updated when a password is changed</value>

        [DataMember(Name="UpdateWindowsServiceOnPasswordChange")]
        public bool? UpdateWindowsServiceOnPasswordChange { get; set; }

        /// <summary>
        /// Flag allowing windows tasks to be updated when a password is changed
        /// </summary>
        /// <value>Flag allowing windows tasks to be updated when a password is changed</value>

        [DataMember(Name="UpdateWindowsTasksOnPasswordChange")]
        public bool? UpdateWindowsTasksOnPasswordChange { get; set; }

        /// <summary>
        /// Flag allowing complus applications to be updated when a password is changed
        /// </summary>
        /// <value>Flag allowing complus applications to be updated when a password is changed</value>

        [DataMember(Name="UpdateComPlusOnPasswordChange")]
        public bool? UpdateComPlusOnPasswordChange { get; set; }

        /// <summary>
        /// Flag allowing Iis Pools to be updated when a password is changed
        /// </summary>
        /// <value>Flag allowing Iis Pools to be updated when a password is changed</value>

        [DataMember(Name="UpdateIisPoolsOnPasswordChange")]
        public bool? UpdateIisPoolsOnPasswordChange { get; set; }

        /// <summary>
        /// Flag allowing this schedule to be updated when a password is manually changed
        /// </summary>
        /// <value>Flag allowing this schedule to be updated when a password is manually changed</value>

        [DataMember(Name="RescheduleForUnscheduledPasswordUpdate")]
        public bool? RescheduleForUnscheduledPasswordUpdate { get; set; }

        /// <summary>
        /// The asset partition this change schedule is applied to (Read-only)
        /// </summary>
        /// <value>The asset partition this change schedule is applied to (Read-only)</value>

        [DataMember(Name="AssetPartitionId")]
        public int? AssetPartitionId { get; set; }

        /// <summary>
        /// Name of the asset partition this change schedule is applied to (Read-only)
        /// </summary>
        /// <value>Name of the asset partition this change schedule is applied to (Read-only)</value>

        [DataMember(Name="AssetPartitionName")]
        public string AssetPartitionName { get; set; }

        /// <summary>
        /// Database ID of the schedule (Read-only)
        /// </summary>
        /// <value>Database ID of the schedule (Read-only)</value>

        [DataMember(Name="Id")]
        public int? Id { get; set; }

        /// <summary>
        /// Description of this schedule
        /// </summary>
        /// <value>Description of this schedule</value>

        [MaxLength(255)]
        [DataMember(Name="Description")]
        public string Description { get; set; }

        /// <summary>
        /// Date this entity was created (Read-only)
        /// </summary>
        /// <value>Date this entity was created (Read-only)</value>

        [DataMember(Name="CreatedDate")]
        public DateTime? CreatedDate { get; set; }

        /// <summary>
        /// The database ID of the user that created this entity (Read-only)
        /// </summary>
        /// <value>The database ID of the user that created this entity (Read-only)</value>

        [DataMember(Name="CreatedByUserId")]
        public int? CreatedByUserId { get; set; }

        /// <summary>
        /// The display name of the user that created this entity (Read-only)
        /// </summary>
        /// <value>The display name of the user that created this entity (Read-only)</value>

        [DataMember(Name="CreatedByUserDisplayName")]
        public string CreatedByUserDisplayName { get; set; }

        /// <summary>
        /// Gets or Sets ScheduleType
        /// </summary>

        [DataMember(Name="ScheduleType")]
        public ScheduleType ScheduleType { get; set; }

        /// <summary>
        /// The timezone in which the schedule should run. Required when ScheduleType is not Never.
        /// </summary>
        /// <value>The timezone in which the schedule should run. Required when ScheduleType is not Never.</value>

        [DataMember(Name="TimeZoneId")]
        public string TimeZoneId { get; set; }

        /// <summary>
        /// The description of the timezone in which the schedule should run (Read-only)
        /// </summary>
        /// <value>The description of the timezone in which the schedule should run (Read-only)</value>

        [DataMember(Name="TimeZoneDisplayName")]
        public string TimeZoneDisplayName { get; set; }

        /// <summary>
        /// How frequently to run. Units are based on ScheduleType.   e.g. every 2 days, every 3 months, every 4 weeks
        /// </summary>
        /// <value>How frequently to run. Units are based on ScheduleType.   e.g. every 2 days, every 3 months, every 4 weeks</value>

        [Range(1, 2147483647)]
        [DataMember(Name="RepeatInterval")]
        public int? RepeatInterval { get; set; }

        /// <summary>
        /// Gets or Sets RepeatMonthlyScheduleType
        /// </summary>

        [DataMember(Name="RepeatMonthlyScheduleType")]
        public MonthlyScheduleType RepeatMonthlyScheduleType { get; set; }

        /// <summary>
        /// Gets or Sets RepeatWeekOfMonth
        /// </summary>

        [DataMember(Name="RepeatWeekOfMonth")]
        public WeekOfMonth RepeatWeekOfMonth { get; set; }

        /// <summary>
        /// Gets or Sets RepeatDayOfWeek
        /// </summary>

        [DataMember(Name="RepeatDayOfWeek")]
        public DayOfWeek RepeatDayOfWeek { get; set; }

        /// <summary>
        /// Which day of the month the schedule should run. Only valid when RepeatMonthlyScheduleType is DayOfMonth
        /// </summary>
        /// <value>Which day of the month the schedule should run. Only valid when RepeatMonthlyScheduleType is DayOfMonth</value>

        [Range(1, 31)]
        [DataMember(Name="RepeatDayOfMonth")]
        public int? RepeatDayOfMonth { get; set; }

        /// <summary>
        /// Which days of the week the schedule should run. Only valid when ScheduleType is Weekly
        /// </summary>
        /// <value>Which days of the week the schedule should run. Only valid when ScheduleType is Weekly</value>

        [DataMember(Name="RepeatDaysOfWeek")]
        public List<DayOfWeek> RepeatDaysOfWeek { get; set; }

        /// <summary>
        /// Gets or Sets TimeOfDayType
        /// </summary>

        [DataMember(Name="TimeOfDayType")]
        public TimeOfDayType TimeOfDayType { get; set; }

        /// <summary>
        /// The hour of the day that the schedule will run (not applicable for &#x27;Hour&#x27; or &#x27;Minute&#x27; schedule type)
        /// </summary>
        /// <value>The hour of the day that the schedule will run (not applicable for &#x27;Hour&#x27; or &#x27;Minute&#x27; schedule type)</value>

        [Range(0, 23)]
        [DataMember(Name="StartHour")]
        public int? StartHour { get; set; }

        /// <summary>
        /// The minute of the hour of the day that the schedule will run (not applicable for &#x27;Minute&#x27; schedule type)
        /// </summary>
        /// <value>The minute of the hour of the day that the schedule will run (not applicable for &#x27;Minute&#x27; schedule type)</value>

        [Range(0, 59)]
        [DataMember(Name="StartMinute")]
        public int? StartMinute { get; set; }

        /// <summary>
        /// Configuration of intervals of time in a day where tasks can be executed.
        /// </summary>
        /// <value>Configuration of intervals of time in a day where tasks can be executed.</value>

        [DataMember(Name="TimeOfDayIntervals")]
        public List<ScheduleInterval> TimeOfDayIntervals { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PasswordChangeSchedule {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  AllowPasswordChangeWhenReleased: ").Append(AllowPasswordChangeWhenReleased).Append("\n");
            sb.Append("  SuspendAccountWhenCheckedIn: ").Append(SuspendAccountWhenCheckedIn).Append("\n");
            sb.Append("  NotifyOwnersOnly: ").Append(NotifyOwnersOnly).Append("\n");
            sb.Append("  RequireCurrentPassword: ").Append(RequireCurrentPassword).Append("\n");
            sb.Append("  RestartWindowsServiceOnPasswordChange: ").Append(RestartWindowsServiceOnPasswordChange).Append("\n");
            sb.Append("  UpdateWindowsServiceOnPasswordChange: ").Append(UpdateWindowsServiceOnPasswordChange).Append("\n");
            sb.Append("  UpdateWindowsTasksOnPasswordChange: ").Append(UpdateWindowsTasksOnPasswordChange).Append("\n");
            sb.Append("  UpdateComPlusOnPasswordChange: ").Append(UpdateComPlusOnPasswordChange).Append("\n");
            sb.Append("  UpdateIisPoolsOnPasswordChange: ").Append(UpdateIisPoolsOnPasswordChange).Append("\n");
            sb.Append("  RescheduleForUnscheduledPasswordUpdate: ").Append(RescheduleForUnscheduledPasswordUpdate).Append("\n");
            sb.Append("  AssetPartitionId: ").Append(AssetPartitionId).Append("\n");
            sb.Append("  AssetPartitionName: ").Append(AssetPartitionName).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("  CreatedByUserId: ").Append(CreatedByUserId).Append("\n");
            sb.Append("  CreatedByUserDisplayName: ").Append(CreatedByUserDisplayName).Append("\n");
            sb.Append("  ScheduleType: ").Append(ScheduleType).Append("\n");
            sb.Append("  TimeZoneId: ").Append(TimeZoneId).Append("\n");
            sb.Append("  TimeZoneDisplayName: ").Append(TimeZoneDisplayName).Append("\n");
            sb.Append("  RepeatInterval: ").Append(RepeatInterval).Append("\n");
            sb.Append("  RepeatMonthlyScheduleType: ").Append(RepeatMonthlyScheduleType).Append("\n");
            sb.Append("  RepeatWeekOfMonth: ").Append(RepeatWeekOfMonth).Append("\n");
            sb.Append("  RepeatDayOfWeek: ").Append(RepeatDayOfWeek).Append("\n");
            sb.Append("  RepeatDayOfMonth: ").Append(RepeatDayOfMonth).Append("\n");
            sb.Append("  RepeatDaysOfWeek: ").Append(RepeatDaysOfWeek).Append("\n");
            sb.Append("  TimeOfDayType: ").Append(TimeOfDayType).Append("\n");
            sb.Append("  StartHour: ").Append(StartHour).Append("\n");
            sb.Append("  StartMinute: ").Append(StartMinute).Append("\n");
            sb.Append("  TimeOfDayIntervals: ").Append(TimeOfDayIntervals).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PasswordChangeSchedule)obj);
        }

        /// <summary>
        /// Returns true if PasswordChangeSchedule instances are equal
        /// </summary>
        /// <param name="other">Instance of PasswordChangeSchedule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PasswordChangeSchedule other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    AllowPasswordChangeWhenReleased == other.AllowPasswordChangeWhenReleased ||
                    AllowPasswordChangeWhenReleased != null &&
                    AllowPasswordChangeWhenReleased.Equals(other.AllowPasswordChangeWhenReleased)
                ) && 
                (
                    SuspendAccountWhenCheckedIn == other.SuspendAccountWhenCheckedIn ||
                    SuspendAccountWhenCheckedIn != null &&
                    SuspendAccountWhenCheckedIn.Equals(other.SuspendAccountWhenCheckedIn)
                ) && 
                (
                    NotifyOwnersOnly == other.NotifyOwnersOnly ||
                    NotifyOwnersOnly != null &&
                    NotifyOwnersOnly.Equals(other.NotifyOwnersOnly)
                ) && 
                (
                    RequireCurrentPassword == other.RequireCurrentPassword ||
                    RequireCurrentPassword != null &&
                    RequireCurrentPassword.Equals(other.RequireCurrentPassword)
                ) && 
                (
                    RestartWindowsServiceOnPasswordChange == other.RestartWindowsServiceOnPasswordChange ||
                    RestartWindowsServiceOnPasswordChange != null &&
                    RestartWindowsServiceOnPasswordChange.Equals(other.RestartWindowsServiceOnPasswordChange)
                ) && 
                (
                    UpdateWindowsServiceOnPasswordChange == other.UpdateWindowsServiceOnPasswordChange ||
                    UpdateWindowsServiceOnPasswordChange != null &&
                    UpdateWindowsServiceOnPasswordChange.Equals(other.UpdateWindowsServiceOnPasswordChange)
                ) && 
                (
                    UpdateWindowsTasksOnPasswordChange == other.UpdateWindowsTasksOnPasswordChange ||
                    UpdateWindowsTasksOnPasswordChange != null &&
                    UpdateWindowsTasksOnPasswordChange.Equals(other.UpdateWindowsTasksOnPasswordChange)
                ) && 
                (
                    UpdateComPlusOnPasswordChange == other.UpdateComPlusOnPasswordChange ||
                    UpdateComPlusOnPasswordChange != null &&
                    UpdateComPlusOnPasswordChange.Equals(other.UpdateComPlusOnPasswordChange)
                ) && 
                (
                    UpdateIisPoolsOnPasswordChange == other.UpdateIisPoolsOnPasswordChange ||
                    UpdateIisPoolsOnPasswordChange != null &&
                    UpdateIisPoolsOnPasswordChange.Equals(other.UpdateIisPoolsOnPasswordChange)
                ) && 
                (
                    RescheduleForUnscheduledPasswordUpdate == other.RescheduleForUnscheduledPasswordUpdate ||
                    RescheduleForUnscheduledPasswordUpdate != null &&
                    RescheduleForUnscheduledPasswordUpdate.Equals(other.RescheduleForUnscheduledPasswordUpdate)
                ) && 
                (
                    AssetPartitionId == other.AssetPartitionId ||
                    AssetPartitionId != null &&
                    AssetPartitionId.Equals(other.AssetPartitionId)
                ) && 
                (
                    AssetPartitionName == other.AssetPartitionName ||
                    AssetPartitionName != null &&
                    AssetPartitionName.Equals(other.AssetPartitionName)
                ) && 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    CreatedDate == other.CreatedDate ||
                    CreatedDate != null &&
                    CreatedDate.Equals(other.CreatedDate)
                ) && 
                (
                    CreatedByUserId == other.CreatedByUserId ||
                    CreatedByUserId != null &&
                    CreatedByUserId.Equals(other.CreatedByUserId)
                ) && 
                (
                    CreatedByUserDisplayName == other.CreatedByUserDisplayName ||
                    CreatedByUserDisplayName != null &&
                    CreatedByUserDisplayName.Equals(other.CreatedByUserDisplayName)
                ) && 
                (
                    ScheduleType == other.ScheduleType ||
                    ScheduleType != null &&
                    ScheduleType.Equals(other.ScheduleType)
                ) && 
                (
                    TimeZoneId == other.TimeZoneId ||
                    TimeZoneId != null &&
                    TimeZoneId.Equals(other.TimeZoneId)
                ) && 
                (
                    TimeZoneDisplayName == other.TimeZoneDisplayName ||
                    TimeZoneDisplayName != null &&
                    TimeZoneDisplayName.Equals(other.TimeZoneDisplayName)
                ) && 
                (
                    RepeatInterval == other.RepeatInterval ||
                    RepeatInterval != null &&
                    RepeatInterval.Equals(other.RepeatInterval)
                ) && 
                (
                    RepeatMonthlyScheduleType == other.RepeatMonthlyScheduleType ||
                    RepeatMonthlyScheduleType != null &&
                    RepeatMonthlyScheduleType.Equals(other.RepeatMonthlyScheduleType)
                ) && 
                (
                    RepeatWeekOfMonth == other.RepeatWeekOfMonth ||
                    RepeatWeekOfMonth != null &&
                    RepeatWeekOfMonth.Equals(other.RepeatWeekOfMonth)
                ) && 
                (
                    RepeatDayOfWeek == other.RepeatDayOfWeek ||
                    RepeatDayOfWeek != null &&
                    RepeatDayOfWeek.Equals(other.RepeatDayOfWeek)
                ) && 
                (
                    RepeatDayOfMonth == other.RepeatDayOfMonth ||
                    RepeatDayOfMonth != null &&
                    RepeatDayOfMonth.Equals(other.RepeatDayOfMonth)
                ) && 
                (
                    RepeatDaysOfWeek == other.RepeatDaysOfWeek ||
                    RepeatDaysOfWeek != null &&
                    RepeatDaysOfWeek.SequenceEqual(other.RepeatDaysOfWeek)
                ) && 
                (
                    TimeOfDayType == other.TimeOfDayType ||
                    TimeOfDayType != null &&
                    TimeOfDayType.Equals(other.TimeOfDayType)
                ) && 
                (
                    StartHour == other.StartHour ||
                    StartHour != null &&
                    StartHour.Equals(other.StartHour)
                ) && 
                (
                    StartMinute == other.StartMinute ||
                    StartMinute != null &&
                    StartMinute.Equals(other.StartMinute)
                ) && 
                (
                    TimeOfDayIntervals == other.TimeOfDayIntervals ||
                    TimeOfDayIntervals != null &&
                    TimeOfDayIntervals.SequenceEqual(other.TimeOfDayIntervals)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (AllowPasswordChangeWhenReleased != null)
                    hashCode = hashCode * 59 + AllowPasswordChangeWhenReleased.GetHashCode();
                    if (SuspendAccountWhenCheckedIn != null)
                    hashCode = hashCode * 59 + SuspendAccountWhenCheckedIn.GetHashCode();
                    if (NotifyOwnersOnly != null)
                    hashCode = hashCode * 59 + NotifyOwnersOnly.GetHashCode();
                    if (RequireCurrentPassword != null)
                    hashCode = hashCode * 59 + RequireCurrentPassword.GetHashCode();
                    if (RestartWindowsServiceOnPasswordChange != null)
                    hashCode = hashCode * 59 + RestartWindowsServiceOnPasswordChange.GetHashCode();
                    if (UpdateWindowsServiceOnPasswordChange != null)
                    hashCode = hashCode * 59 + UpdateWindowsServiceOnPasswordChange.GetHashCode();
                    if (UpdateWindowsTasksOnPasswordChange != null)
                    hashCode = hashCode * 59 + UpdateWindowsTasksOnPasswordChange.GetHashCode();
                    if (UpdateComPlusOnPasswordChange != null)
                    hashCode = hashCode * 59 + UpdateComPlusOnPasswordChange.GetHashCode();
                    if (UpdateIisPoolsOnPasswordChange != null)
                    hashCode = hashCode * 59 + UpdateIisPoolsOnPasswordChange.GetHashCode();
                    if (RescheduleForUnscheduledPasswordUpdate != null)
                    hashCode = hashCode * 59 + RescheduleForUnscheduledPasswordUpdate.GetHashCode();
                    if (AssetPartitionId != null)
                    hashCode = hashCode * 59 + AssetPartitionId.GetHashCode();
                    if (AssetPartitionName != null)
                    hashCode = hashCode * 59 + AssetPartitionName.GetHashCode();
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (CreatedDate != null)
                    hashCode = hashCode * 59 + CreatedDate.GetHashCode();
                    if (CreatedByUserId != null)
                    hashCode = hashCode * 59 + CreatedByUserId.GetHashCode();
                    if (CreatedByUserDisplayName != null)
                    hashCode = hashCode * 59 + CreatedByUserDisplayName.GetHashCode();
                    if (ScheduleType != null)
                    hashCode = hashCode * 59 + ScheduleType.GetHashCode();
                    if (TimeZoneId != null)
                    hashCode = hashCode * 59 + TimeZoneId.GetHashCode();
                    if (TimeZoneDisplayName != null)
                    hashCode = hashCode * 59 + TimeZoneDisplayName.GetHashCode();
                    if (RepeatInterval != null)
                    hashCode = hashCode * 59 + RepeatInterval.GetHashCode();
                    if (RepeatMonthlyScheduleType != null)
                    hashCode = hashCode * 59 + RepeatMonthlyScheduleType.GetHashCode();
                    if (RepeatWeekOfMonth != null)
                    hashCode = hashCode * 59 + RepeatWeekOfMonth.GetHashCode();
                    if (RepeatDayOfWeek != null)
                    hashCode = hashCode * 59 + RepeatDayOfWeek.GetHashCode();
                    if (RepeatDayOfMonth != null)
                    hashCode = hashCode * 59 + RepeatDayOfMonth.GetHashCode();
                    if (RepeatDaysOfWeek != null)
                    hashCode = hashCode * 59 + RepeatDaysOfWeek.GetHashCode();
                    if (TimeOfDayType != null)
                    hashCode = hashCode * 59 + TimeOfDayType.GetHashCode();
                    if (StartHour != null)
                    hashCode = hashCode * 59 + StartHour.GetHashCode();
                    if (StartMinute != null)
                    hashCode = hashCode * 59 + StartMinute.GetHashCode();
                    if (TimeOfDayIntervals != null)
                    hashCode = hashCode * 59 + TimeOfDayIntervals.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PasswordChangeSchedule left, PasswordChangeSchedule right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PasswordChangeSchedule left, PasswordChangeSchedule right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
