/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
        /// <summary>
        /// Gets or Sets PatchStagingStatus
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PatchStagingStatus
        {
            /// <summary>
            /// Enum NoneEnum for None
            /// </summary>
            [EnumMember(Value = "None")]
            NoneEnum = 0,
            /// <summary>
            /// Enum StagingEnum for Staging
            /// </summary>
            [EnumMember(Value = "Staging")]
            StagingEnum = 1,
            /// <summary>
            /// Enum UnstagingEnum for Unstaging
            /// </summary>
            [EnumMember(Value = "Unstaging")]
            UnstagingEnum = 2,
            /// <summary>
            /// Enum StagedEnum for Staged
            /// </summary>
            [EnumMember(Value = "Staged")]
            StagedEnum = 3,
            /// <summary>
            /// Enum ErrorEnum for Error
            /// </summary>
            [EnumMember(Value = "Error")]
            ErrorEnum = 4,
            /// <summary>
            /// Enum WaitingEnum for Waiting
            /// </summary>
            [EnumMember(Value = "Waiting")]
            WaitingEnum = 5        }
}
