/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
    /// <summary>
    /// Configuration specific to Remote Desktop application sessions
    /// </summary>
    [DataContract]
    public partial class RemoteDesktopApplicationProperties : IEquatable<RemoteDesktopApplicationProperties>
    { 
        /// <summary>
        /// Database ID fo the application host asset
        /// </summary>
        /// <value>Database ID fo the application host asset</value>

        [DataMember(Name="ApplicationHostAssetId")]
        public int? ApplicationHostAssetId { get; set; }

        /// <summary>
        /// Gets or Sets ApplicationHostAsset
        /// </summary>

        [DataMember(Name="ApplicationHostAsset")]
        public PolicyAsset ApplicationHostAsset { get; set; }

        /// <summary>
        /// Database ID fo the application host asset login account
        /// </summary>
        /// <value>Database ID fo the application host asset login account</value>

        [DataMember(Name="ApplicationHostAccountId")]
        public int? ApplicationHostAccountId { get; set; }

        /// <summary>
        /// Gets or Sets ApplicationHostLoginAccount
        /// </summary>

        [DataMember(Name="ApplicationHostLoginAccount")]
        public PolicyAccount ApplicationHostLoginAccount { get; set; }

        /// <summary>
        /// Remote application display name
        /// </summary>
        /// <value>Remote application display name</value>

        [MaxLength(50)]
        [DataMember(Name="ApplicationDisplayName")]
        public string ApplicationDisplayName { get; set; }

        /// <summary>
        /// Remote application alias
        /// </summary>
        /// <value>Remote application alias</value>

        [MaxLength(1000)]
        [DataMember(Name="ApplicationAlias")]
        public string ApplicationAlias { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RemoteDesktopApplicationProperties {\n");
            sb.Append("  ApplicationHostAssetId: ").Append(ApplicationHostAssetId).Append("\n");
            sb.Append("  ApplicationHostAsset: ").Append(ApplicationHostAsset).Append("\n");
            sb.Append("  ApplicationHostAccountId: ").Append(ApplicationHostAccountId).Append("\n");
            sb.Append("  ApplicationHostLoginAccount: ").Append(ApplicationHostLoginAccount).Append("\n");
            sb.Append("  ApplicationDisplayName: ").Append(ApplicationDisplayName).Append("\n");
            sb.Append("  ApplicationAlias: ").Append(ApplicationAlias).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RemoteDesktopApplicationProperties)obj);
        }

        /// <summary>
        /// Returns true if RemoteDesktopApplicationProperties instances are equal
        /// </summary>
        /// <param name="other">Instance of RemoteDesktopApplicationProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RemoteDesktopApplicationProperties other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ApplicationHostAssetId == other.ApplicationHostAssetId ||
                    ApplicationHostAssetId != null &&
                    ApplicationHostAssetId.Equals(other.ApplicationHostAssetId)
                ) && 
                (
                    ApplicationHostAsset == other.ApplicationHostAsset ||
                    ApplicationHostAsset != null &&
                    ApplicationHostAsset.Equals(other.ApplicationHostAsset)
                ) && 
                (
                    ApplicationHostAccountId == other.ApplicationHostAccountId ||
                    ApplicationHostAccountId != null &&
                    ApplicationHostAccountId.Equals(other.ApplicationHostAccountId)
                ) && 
                (
                    ApplicationHostLoginAccount == other.ApplicationHostLoginAccount ||
                    ApplicationHostLoginAccount != null &&
                    ApplicationHostLoginAccount.Equals(other.ApplicationHostLoginAccount)
                ) && 
                (
                    ApplicationDisplayName == other.ApplicationDisplayName ||
                    ApplicationDisplayName != null &&
                    ApplicationDisplayName.Equals(other.ApplicationDisplayName)
                ) && 
                (
                    ApplicationAlias == other.ApplicationAlias ||
                    ApplicationAlias != null &&
                    ApplicationAlias.Equals(other.ApplicationAlias)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ApplicationHostAssetId != null)
                    hashCode = hashCode * 59 + ApplicationHostAssetId.GetHashCode();
                    if (ApplicationHostAsset != null)
                    hashCode = hashCode * 59 + ApplicationHostAsset.GetHashCode();
                    if (ApplicationHostAccountId != null)
                    hashCode = hashCode * 59 + ApplicationHostAccountId.GetHashCode();
                    if (ApplicationHostLoginAccount != null)
                    hashCode = hashCode * 59 + ApplicationHostLoginAccount.GetHashCode();
                    if (ApplicationDisplayName != null)
                    hashCode = hashCode * 59 + ApplicationDisplayName.GetHashCode();
                    if (ApplicationAlias != null)
                    hashCode = hashCode * 59 + ApplicationAlias.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RemoteDesktopApplicationProperties left, RemoteDesktopApplicationProperties right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RemoteDesktopApplicationProperties left, RemoteDesktopApplicationProperties right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
