/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
    /// <summary>
    /// A license for the secrets broker module.
    /// </summary>
    [DataContract]
    public partial class SecretsBrokerLicense : IEquatable<SecretsBrokerLicense>
    { 
        /// <summary>
        /// The maximum number of secrets permitted under this license.
        /// </summary>
        /// <value>The maximum number of secrets permitted under this license.</value>

        [DataMember(Name="MaxSecrets")]
        public int? MaxSecrets { get; set; }

        /// <summary>
        /// The number of secrets currently utilized.
        /// </summary>
        /// <value>The number of secrets currently utilized.</value>

        [DataMember(Name="SecretsUsed")]
        public int? SecretsUsed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SecretsBrokerLicense {\n");
            sb.Append("  MaxSecrets: ").Append(MaxSecrets).Append("\n");
            sb.Append("  SecretsUsed: ").Append(SecretsUsed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SecretsBrokerLicense)obj);
        }

        /// <summary>
        /// Returns true if SecretsBrokerLicense instances are equal
        /// </summary>
        /// <param name="other">Instance of SecretsBrokerLicense to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SecretsBrokerLicense other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MaxSecrets == other.MaxSecrets ||
                    MaxSecrets != null &&
                    MaxSecrets.Equals(other.MaxSecrets)
                ) && 
                (
                    SecretsUsed == other.SecretsUsed ||
                    SecretsUsed != null &&
                    SecretsUsed.Equals(other.SecretsUsed)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (MaxSecrets != null)
                    hashCode = hashCode * 59 + MaxSecrets.GetHashCode();
                    if (SecretsUsed != null)
                    hashCode = hashCode * 59 + SecretsUsed.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SecretsBrokerLicense left, SecretsBrokerLicense right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SecretsBrokerLicense left, SecretsBrokerLicense right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
