/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
    /// <summary>
    /// Properties for syslog subscribers
    /// </summary>
    [DataContract]
    public partial class SyslogSubscriberProperties : IEquatable<SyslogSubscriberProperties>
    { 
        /// <summary>
        /// The syslog server configuration to use
        /// </summary>
        /// <value>The syslog server configuration to use</value>

        [DataMember(Name="SyslogServerId")]
        public int? SyslogServerId { get; set; }

        /// <summary>
        /// Name of the syslog server configuration
        /// </summary>
        /// <value>Name of the syslog server configuration</value>

        [MaxLength(50)]
        [DataMember(Name="SyslogServerName")]
        public string SyslogServerName { get; set; }

        /// <summary>
        /// Network address of syslog server. If server ID is not specified than server will be looked up by network address
        /// </summary>
        /// <value>Network address of syslog server. If server ID is not specified than server will be looked up by network address</value>

        [MaxLength(255)]
        [DataMember(Name="NetworkAddress")]
        public string NetworkAddress { get; set; }

        /// <summary>
        /// Port to connect to syslog server
        /// </summary>
        /// <value>Port to connect to syslog server</value>

        [Range(1, 32767)]
        [DataMember(Name="Port")]
        public int? Port { get; set; }

        /// <summary>
        /// Whether to encrypt data with SSL. Only valid when using TCP protocol.
        /// </summary>
        /// <value>Whether to encrypt data with SSL. Only valid when using TCP protocol.</value>

        [DataMember(Name="UseSslEncryption")]
        public bool? UseSslEncryption { get; set; }

        /// <summary>
        /// Whether to authenticate to syslog server with client certificate. Requires that SyslogClientCertificate is configured. Only valid when using SSL encryption
        /// </summary>
        /// <value>Whether to authenticate to syslog server with client certificate. Requires that SyslogClientCertificate is configured. Only valid when using SSL encryption</value>

        [DataMember(Name="UseClientCertificate")]
        public bool? UseClientCertificate { get; set; }

        /// <summary>
        /// Verify SSL certificate if using SSL. Only valid when using SSL encryption
        /// </summary>
        /// <value>Verify SSL certificate if using SSL. Only valid when using SSL encryption</value>

        [DataMember(Name="VerifySslCertificate")]
        public bool? VerifySslCertificate { get; set; }

        /// <summary>
        /// Gets or Sets Facility
        /// </summary>

        [DataMember(Name="Facility")]
        public SyslogFacility Facility { get; set; }

        /// <summary>
        /// All event properties with this prefix (Only for Json log format)
        /// </summary>
        /// <value>All event properties with this prefix (Only for Json log format)</value>

        [MaxLength(50)]
        [DataMember(Name="KeyPrefix")]
        public string KeyPrefix { get; set; }

        /// <summary>
        /// Gets or Sets Protocol
        /// </summary>

        [DataMember(Name="Protocol")]
        public SyslogProtocol Protocol { get; set; }

        /// <summary>
        /// Gets or Sets LogFormat
        /// </summary>

        [DataMember(Name="LogFormat")]
        public SyslogFormat LogFormat { get; set; }

        /// <summary>
        /// Gets or Sets TcpFraming
        /// </summary>

        [DataMember(Name="TcpFraming")]
        public SyslogTcpFraming TcpFraming { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SyslogSubscriberProperties {\n");
            sb.Append("  SyslogServerId: ").Append(SyslogServerId).Append("\n");
            sb.Append("  SyslogServerName: ").Append(SyslogServerName).Append("\n");
            sb.Append("  NetworkAddress: ").Append(NetworkAddress).Append("\n");
            sb.Append("  Port: ").Append(Port).Append("\n");
            sb.Append("  UseSslEncryption: ").Append(UseSslEncryption).Append("\n");
            sb.Append("  UseClientCertificate: ").Append(UseClientCertificate).Append("\n");
            sb.Append("  VerifySslCertificate: ").Append(VerifySslCertificate).Append("\n");
            sb.Append("  Facility: ").Append(Facility).Append("\n");
            sb.Append("  KeyPrefix: ").Append(KeyPrefix).Append("\n");
            sb.Append("  Protocol: ").Append(Protocol).Append("\n");
            sb.Append("  LogFormat: ").Append(LogFormat).Append("\n");
            sb.Append("  TcpFraming: ").Append(TcpFraming).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SyslogSubscriberProperties)obj);
        }

        /// <summary>
        /// Returns true if SyslogSubscriberProperties instances are equal
        /// </summary>
        /// <param name="other">Instance of SyslogSubscriberProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SyslogSubscriberProperties other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    SyslogServerId == other.SyslogServerId ||
                    SyslogServerId != null &&
                    SyslogServerId.Equals(other.SyslogServerId)
                ) && 
                (
                    SyslogServerName == other.SyslogServerName ||
                    SyslogServerName != null &&
                    SyslogServerName.Equals(other.SyslogServerName)
                ) && 
                (
                    NetworkAddress == other.NetworkAddress ||
                    NetworkAddress != null &&
                    NetworkAddress.Equals(other.NetworkAddress)
                ) && 
                (
                    Port == other.Port ||
                    Port != null &&
                    Port.Equals(other.Port)
                ) && 
                (
                    UseSslEncryption == other.UseSslEncryption ||
                    UseSslEncryption != null &&
                    UseSslEncryption.Equals(other.UseSslEncryption)
                ) && 
                (
                    UseClientCertificate == other.UseClientCertificate ||
                    UseClientCertificate != null &&
                    UseClientCertificate.Equals(other.UseClientCertificate)
                ) && 
                (
                    VerifySslCertificate == other.VerifySslCertificate ||
                    VerifySslCertificate != null &&
                    VerifySslCertificate.Equals(other.VerifySslCertificate)
                ) && 
                (
                    Facility == other.Facility ||
                    Facility != null &&
                    Facility.Equals(other.Facility)
                ) && 
                (
                    KeyPrefix == other.KeyPrefix ||
                    KeyPrefix != null &&
                    KeyPrefix.Equals(other.KeyPrefix)
                ) && 
                (
                    Protocol == other.Protocol ||
                    Protocol != null &&
                    Protocol.Equals(other.Protocol)
                ) && 
                (
                    LogFormat == other.LogFormat ||
                    LogFormat != null &&
                    LogFormat.Equals(other.LogFormat)
                ) && 
                (
                    TcpFraming == other.TcpFraming ||
                    TcpFraming != null &&
                    TcpFraming.Equals(other.TcpFraming)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (SyslogServerId != null)
                    hashCode = hashCode * 59 + SyslogServerId.GetHashCode();
                    if (SyslogServerName != null)
                    hashCode = hashCode * 59 + SyslogServerName.GetHashCode();
                    if (NetworkAddress != null)
                    hashCode = hashCode * 59 + NetworkAddress.GetHashCode();
                    if (Port != null)
                    hashCode = hashCode * 59 + Port.GetHashCode();
                    if (UseSslEncryption != null)
                    hashCode = hashCode * 59 + UseSslEncryption.GetHashCode();
                    if (UseClientCertificate != null)
                    hashCode = hashCode * 59 + UseClientCertificate.GetHashCode();
                    if (VerifySslCertificate != null)
                    hashCode = hashCode * 59 + VerifySslCertificate.GetHashCode();
                    if (Facility != null)
                    hashCode = hashCode * 59 + Facility.GetHashCode();
                    if (KeyPrefix != null)
                    hashCode = hashCode * 59 + KeyPrefix.GetHashCode();
                    if (Protocol != null)
                    hashCode = hashCode * 59 + Protocol.GetHashCode();
                    if (LogFormat != null)
                    hashCode = hashCode * 59 + LogFormat.GetHashCode();
                    if (TcpFraming != null)
                    hashCode = hashCode * 59 + TcpFraming.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SyslogSubscriberProperties left, SyslogSubscriberProperties right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SyslogSubscriberProperties left, SyslogSubscriberProperties right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
