/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OneIdentitySafeguard.Mock.Server.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TaggingGroupingRule : IEquatable<TaggingGroupingRule>
    { 
        /// <summary>
        /// Description of the rule
        /// </summary>
        /// <value>Description of the rule</value>

        [MaxLength(255)]
        [DataMember(Name="Description")]
        public string Description { get; set; }

        /// <summary>
        /// If true, entities will be evaluated against this rule
        /// </summary>
        /// <value>If true, entities will be evaluated against this rule</value>

        [DataMember(Name="Enabled")]
        public bool? Enabled { get; set; }

        /// <summary>
        /// Gets or Sets RuleConditionGroup
        /// </summary>

        [DataMember(Name="RuleConditionGroup")]
        public TaggingGroupingConditionGroup RuleConditionGroup { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaggingGroupingRule {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  RuleConditionGroup: ").Append(RuleConditionGroup).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TaggingGroupingRule)obj);
        }

        /// <summary>
        /// Returns true if TaggingGroupingRule instances are equal
        /// </summary>
        /// <param name="other">Instance of TaggingGroupingRule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaggingGroupingRule other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    Enabled == other.Enabled ||
                    Enabled != null &&
                    Enabled.Equals(other.Enabled)
                ) && 
                (
                    RuleConditionGroup == other.RuleConditionGroup ||
                    RuleConditionGroup != null &&
                    RuleConditionGroup.Equals(other.RuleConditionGroup)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (Enabled != null)
                    hashCode = hashCode * 59 + Enabled.GetHashCode();
                    if (RuleConditionGroup != null)
                    hashCode = hashCode * 59 + RuleConditionGroup.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TaggingGroupingRule left, TaggingGroupingRule right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TaggingGroupingRule left, TaggingGroupingRule right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
