/*
 * Safeguard Core API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using OneIdentitySafeguard.Mock.Server.Attributes;
using OneIdentitySafeguard.Mock.Server.Security;
using Microsoft.AspNetCore.Authorization;
using OneIdentitySafeguard.Mock.Server.Models;

namespace OneIdentitySafeguard.Mock.Server.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class TicketSystemsApiController : ControllerBase
    { 
        /// <summary>
        /// Creates a new ticket system
        /// </summary>
        /// <param name="body">ticket system to create</param>
        /// <response code="201">Created</response>
        /// <response code="400">Bad Request</response>
        /// <response code="403">Must have ApplianceAdmin permission</response>
        /// <response code="404">ticket system not found</response>
        [HttpPost]
        [Route("/service/core/v4/TicketSystems")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("TicketSystemsCreateEntityAsync")]
        [SwaggerResponse(statusCode: 201, type: typeof(TicketSystem), description: "Created")]
        [SwaggerResponse(statusCode: 400, type: typeof(ApiError), description: "Bad Request")]
        [SwaggerResponse(statusCode: 403, type: typeof(ApiError), description: "Must have ApplianceAdmin permission")]
        public virtual IActionResult TicketSystemsCreateEntityAsync([FromBody]TicketSystem body)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(TicketSystem));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ApiError));

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(ApiError));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "{\n  \"UserName\" : \"UserName\",\n  \"TicketSystemType\" : \"ServiceNow\",\n  \"Name\" : \"Name\",\n  \"ApplicationUrl\" : \"ApplicationUrl\",\n  \"CreatedByUserId\" : 6,\n  \"RemedyProperties\" : {\n    \"AuthenticationString\" : \"AuthenticationString\"\n  },\n  \"ServiceNowProperties\" : {\n    \"ClientIdentifier\" : \"ClientIdentifier\",\n    \"ClientSecret\" : \"ClientSecret\",\n    \"HasClientSecret\" : true\n  },\n  \"CreatedDate\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"CreatedByUserDisplayName\" : \"CreatedByUserDisplayName\",\n  \"Id\" : 0,\n  \"TicketRegularExpression\" : \"TicketRegularExpression\",\n  \"HasPassword\" : true,\n  \"Password\" : \"Password\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<TicketSystem>(exampleJson)
                        : default(TicketSystem);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Removes a ticket system
        /// </summary>
        /// <param name="id">Unique identifier of the ticket system</param>
        /// <response code="204">Success - No Content</response>
        /// <response code="403">Must have ApplianceAdmin permission</response>
        [HttpDelete]
        [Route("/service/core/v4/TicketSystems/{id}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("TicketSystemsDeleteAsync")]
        [SwaggerResponse(statusCode: 403, type: typeof(ApiError), description: "Must have ApplianceAdmin permission")]
        public virtual IActionResult TicketSystemsDeleteAsync([FromRoute][Required]int? id)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(ApiError));

            throw new NotImplementedException();
        }

        /// <summary>
        /// Gets a list of all ticket systems
        /// </summary>
        /// <param name="filter">Filter results. Available operators: eq, ne, gt, ge, lt, le, and, or, not, contains, ieq, icontains, in [ {item1}, {item2}, etc], (). Use \\ to escape quotes in strings.</param>
        /// <param name="page">Which page (starting with 0) of data to return</param>
        /// <param name="limit">The size of a page of data</param>
        /// <param name="count">When specified, the method will return a single integer value representing the total number of items that match the given filter criteria. If specified, the fields and orderby parameter values are ignored.</param>
        /// <param name="fields">List of property names (comma-separated) to include in entity output. Prepend list with - to exclude from output.</param>
        /// <param name="orderby">List of property names (comma-separated) to sort entities by. Prepend properties with - for  descending.</param>
        /// <param name="q">Search all string fields for the specified value</param>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Must be an authenticated user</response>
        /// <response code="403">Forbidden</response>
        [HttpGet]
        [Route("/service/core/v4/TicketSystems")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("TicketSystemsGetAsync")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<TicketSystem>), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ApiError), description: "Bad Request")]
        [SwaggerResponse(statusCode: 403, type: typeof(ApiError), description: "Forbidden")]
        public virtual IActionResult TicketSystemsGetAsync([FromQuery]string filter, [FromQuery]int? page, [FromQuery]int? limit, [FromQuery]bool? count, [FromQuery]string fields, [FromQuery]string orderby, [FromQuery]string q)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<TicketSystem>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ApiError));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(ApiError));
            string exampleJson = null;
            exampleJson = "[ {\n  \"UserName\" : \"UserName\",\n  \"TicketSystemType\" : \"ServiceNow\",\n  \"Name\" : \"Name\",\n  \"ApplicationUrl\" : \"ApplicationUrl\",\n  \"CreatedByUserId\" : 6,\n  \"RemedyProperties\" : {\n    \"AuthenticationString\" : \"AuthenticationString\"\n  },\n  \"ServiceNowProperties\" : {\n    \"ClientIdentifier\" : \"ClientIdentifier\",\n    \"ClientSecret\" : \"ClientSecret\",\n    \"HasClientSecret\" : true\n  },\n  \"CreatedDate\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"CreatedByUserDisplayName\" : \"CreatedByUserDisplayName\",\n  \"Id\" : 0,\n  \"TicketRegularExpression\" : \"TicketRegularExpression\",\n  \"HasPassword\" : true,\n  \"Password\" : \"Password\"\n}, {\n  \"UserName\" : \"UserName\",\n  \"TicketSystemType\" : \"ServiceNow\",\n  \"Name\" : \"Name\",\n  \"ApplicationUrl\" : \"ApplicationUrl\",\n  \"CreatedByUserId\" : 6,\n  \"RemedyProperties\" : {\n    \"AuthenticationString\" : \"AuthenticationString\"\n  },\n  \"ServiceNowProperties\" : {\n    \"ClientIdentifier\" : \"ClientIdentifier\",\n    \"ClientSecret\" : \"ClientSecret\",\n    \"HasClientSecret\" : true\n  },\n  \"CreatedDate\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"CreatedByUserDisplayName\" : \"CreatedByUserDisplayName\",\n  \"Id\" : 0,\n  \"TicketRegularExpression\" : \"TicketRegularExpression\",\n  \"HasPassword\" : true,\n  \"Password\" : \"Password\"\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<TicketSystem>>(exampleJson)
                        : default(List<TicketSystem>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Gets a ticket system
        /// </summary>
        /// <param name="id">Unique ID of ticket system</param>
        /// <param name="fields">List of property names to include in entity output</param>
        /// <response code="200">Success</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Must be an authenticated user</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">ticket system does not exist</response>
        [HttpGet]
        [Route("/service/core/v4/TicketSystems/{id}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("TicketSystemsGetByIdAsync")]
        [SwaggerResponse(statusCode: 200, type: typeof(TicketSystem), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ApiError), description: "Bad Request")]
        [SwaggerResponse(statusCode: 403, type: typeof(ApiError), description: "Forbidden")]
        public virtual IActionResult TicketSystemsGetByIdAsync([FromRoute][Required]int? id, [FromQuery]string fields)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(TicketSystem));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ApiError));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(ApiError));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "{\n  \"UserName\" : \"UserName\",\n  \"TicketSystemType\" : \"ServiceNow\",\n  \"Name\" : \"Name\",\n  \"ApplicationUrl\" : \"ApplicationUrl\",\n  \"CreatedByUserId\" : 6,\n  \"RemedyProperties\" : {\n    \"AuthenticationString\" : \"AuthenticationString\"\n  },\n  \"ServiceNowProperties\" : {\n    \"ClientIdentifier\" : \"ClientIdentifier\",\n    \"ClientSecret\" : \"ClientSecret\",\n    \"HasClientSecret\" : true\n  },\n  \"CreatedDate\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"CreatedByUserDisplayName\" : \"CreatedByUserDisplayName\",\n  \"Id\" : 0,\n  \"TicketRegularExpression\" : \"TicketRegularExpression\",\n  \"HasPassword\" : true,\n  \"Password\" : \"Password\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<TicketSystem>(exampleJson)
                        : default(TicketSystem);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Test connection parameters to a ticket system
        /// </summary>
        /// <param name="body">ticket system configuration to test</param>
        /// <response code="204">Success</response>
        /// <response code="400">Bad Request</response>
        /// <response code="403">Must have ApplianceAdmin permission</response>
        /// <response code="404">ticket system not found</response>
        [HttpPost]
        [Route("/service/core/v4/TicketSystems/TestConnection")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("TicketSystemsTestConnectionAsync")]
        [SwaggerResponse(statusCode: 400, type: typeof(ApiError), description: "Bad Request")]
        [SwaggerResponse(statusCode: 403, type: typeof(ApiError), description: "Must have ApplianceAdmin permission")]
        public virtual IActionResult TicketSystemsTestConnectionAsync([FromBody]TicketSystemTestConnectionParameters body)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ApiError));

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(ApiError));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Test connection parameters to a ticket system
        /// </summary>
        /// <param name="id">Unique identifier of the ticket system</param>
        /// <response code="204">Success</response>
        /// <response code="403">Must have ApplianceAdmin permission</response>
        /// <response code="404">ticket system not found</response>
        [HttpPost]
        [Route("/service/core/v4/TicketSystems/{id}/TestConnection")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("TicketSystemsTestConnectionByIdAsync")]
        [SwaggerResponse(statusCode: 403, type: typeof(ApiError), description: "Must have ApplianceAdmin permission")]
        public virtual IActionResult TicketSystemsTestConnectionByIdAsync([FromRoute][Required]int? id)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(ApiError));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Updates an existing ticket system
        /// </summary>
        /// <param name="id">Unique identifier of the ticket system</param>
        /// <param name="body">Updated ticket system</param>
        /// <response code="200">Success</response>
        /// <response code="400">60102 - id value does not match the resource URI</response>
        /// <response code="403">Must have ApplianceAdmin permission</response>
        /// <response code="404">TicketSystem does not exist</response>
        [HttpPut]
        [Route("/service/core/v4/TicketSystems/{id}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("TicketSystemsUpdateEntityAsync")]
        [SwaggerResponse(statusCode: 200, type: typeof(TicketSystem), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ApiError), description: "60102 - id value does not match the resource URI")]
        [SwaggerResponse(statusCode: 403, type: typeof(ApiError), description: "Must have ApplianceAdmin permission")]
        public virtual IActionResult TicketSystemsUpdateEntityAsync([FromRoute][Required]int? id, [FromBody]TicketSystem body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(TicketSystem));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ApiError));

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(ApiError));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "{\n  \"UserName\" : \"UserName\",\n  \"TicketSystemType\" : \"ServiceNow\",\n  \"Name\" : \"Name\",\n  \"ApplicationUrl\" : \"ApplicationUrl\",\n  \"CreatedByUserId\" : 6,\n  \"RemedyProperties\" : {\n    \"AuthenticationString\" : \"AuthenticationString\"\n  },\n  \"ServiceNowProperties\" : {\n    \"ClientIdentifier\" : \"ClientIdentifier\",\n    \"ClientSecret\" : \"ClientSecret\",\n    \"HasClientSecret\" : true\n  },\n  \"CreatedDate\" : \"2000-01-23T04:56:07.000+00:00\",\n  \"CreatedByUserDisplayName\" : \"CreatedByUserDisplayName\",\n  \"Id\" : 0,\n  \"TicketRegularExpression\" : \"TicketRegularExpression\",\n  \"HasPassword\" : true,\n  \"Password\" : \"Password\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<TicketSystem>(exampleJson)
                        : default(TicketSystem);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Validate ticket number against all the ticket systems
        /// </summary>
        /// <param name="ticket">Ticket number from ticket system</param>
        /// <response code="200">Created</response>
        /// <response code="401">Must be an authenticated user</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">ticket system not found</response>
        [HttpPost]
        [Route("/service/core/v4/TicketSystems/ValidateTicket/{ticket}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("TicketSystemsValidateAnyTicketAsync")]
        [SwaggerResponse(statusCode: 200, type: typeof(bool?), description: "Created")]
        [SwaggerResponse(statusCode: 403, type: typeof(ApiError), description: "Forbidden")]
        public virtual IActionResult TicketSystemsValidateAnyTicketAsync([FromRoute][Required]string ticket)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(bool?));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(ApiError));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "true";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<bool?>(exampleJson)
                        : default(bool?);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Validate ticket number against the ticket system
        /// </summary>
        /// <param name="id">Unique identifier of the ticket system</param>
        /// <param name="ticket">Ticket number from ticket system</param>
        /// <response code="204">Successfully validated</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Must be an authenticated user</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">ticket system not found</response>
        [HttpPost]
        [Route("/service/core/v4/TicketSystems/{id}/ValidateTicket/{ticket}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("TicketSystemsValidateTicketAsync")]
        [SwaggerResponse(statusCode: 400, type: typeof(ApiError), description: "Bad Request")]
        [SwaggerResponse(statusCode: 403, type: typeof(ApiError), description: "Forbidden")]
        public virtual IActionResult TicketSystemsValidateTicketAsync([FromRoute][Required]int? id, [FromRoute][Required]string ticket)
        { 
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ApiError));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default(ApiError));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }
    }
}
